import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
const repo = resolve(dirname(fileURLToPath(import.meta.url)), '../../..');
const read = file => readFileSync(resolve(repo, file), 'utf8');
const cfg = JSON.parse(read('apps/mobile/capacitor/capacitor.config.json'));
const pkg = JSON.parse(read('apps/mobile/capacitor/package.json'));
const html = read('apps/athlete/conditioning/index.html');
const bundle = read('apps/athlete/conditioning/native-plugins.js');
const ship = read('apps/mobile/capacitor/scripts/ship-capgo.sh');
const gradle = read('apps/mobile/capacitor/android/app/capacitor.build.gradle');
const settings = read('apps/mobile/capacitor/android/capacitor.settings.gradle');
const failures = [];
const must = (condition, message) => { if (!condition) failures.push(message); };
must(pkg.dependencies['@capgo/capacitor-updater'], 'Capgo dependency installed');
must(cfg.webDir === '../../athlete/conditioning', 'native app uses the new HTML');
must(cfg.plugins?.CapacitorUpdater?.autoUpdate === 'onlyDownload', 'updates download without interrupting workouts');
must(cfg.plugins?.CapacitorUpdater?.defaultChannel === 'engine-html', 'new HTML uses its own channel');
must(html.includes('updater.notifyAppReady()'), 'new HTML confirms a successful boot');
must(html.includes('await EngineUpdates.ready()'), 'runtime calls the startup handshake');
must(bundle.includes('CapacitorUpdater'), 'official updater bundled');
must(html.includes('Check for updates') && html.includes('Restart now'), 'Settings offers check and restart');
must(html.includes('activeWorkout()') && html.includes('await window.EngineApp.flushStorage()'), 'restart guards and saves workout data');
must(gradle.includes("project(':capgo-capacitor-updater')"), 'Android links updater');
must(settings.includes("include ':capgo-capacitor-updater'"), 'Android includes updater');
must(ship.includes('scripts/conditioning/build.mjs'), 'publish builds the new HTML');
must(!ship.includes('sync-athlete-app.sh') && !ship.includes('--path ../../athlete'), 'publish avoids the old app root');
must(ship.includes('--min-update-version 1.1.1'), 'bundle declares the new native-shell requirement');
if (failures.length) {
  console.error('capgo-live-update.smoke FAIL');
  failures.forEach(f => console.error(' - ' + f));
  process.exit(1);
}
console.log('capgo-live-update.smoke: ok — new HTML, boot confirmation, isolated channel and safe restart');
