import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
const repo=resolve(dirname(fileURLToPath(import.meta.url)), '../../..');
const read=file=>readFileSync(resolve(repo,file),'utf8');
const config=JSON.parse(read('apps/mobile/capacitor/capacitor.config.json'));
const pkg=JSON.parse(read('apps/mobile/capacitor/package.json'));
assert.equal(config.appId,'com.hybrid.strength');
assert.equal(config.webDir,'../../athlete');
assert.equal(config.plugins.CapacitorUpdater.defaultChannel,'strength-live');
assert.equal(config.plugins.CapacitorUpdater.autoUpdate,'onlyDownload');
assert.equal(pkg.dependencies['@capgo/capacitor-updater'],'8.52.1');
assert.ok(read('apps/athlete/index.html').includes('capgo-updates.js'));
assert.ok(read('apps/athlete/capgo-updates.js').includes('notifyAppReady'));
assert.ok(read('apps/athlete/native-bridge.js').includes("kind: 'kill'"));
const ship=read('apps/mobile/capacitor/scripts/ship-capgo.sh');
assert.ok(ship.includes('--min-update-version 1.3.0'));
assert.ok(ship.includes('--path ../../athlete --channel strength-live'));
assert.ok(!ship.includes('conditioning/'));
console.log('capgo-live-update: strength app ID, channel, native dependency and safe update configuration verified');
