functionsDirectory = "/workspace/apps/mobile/preview-site/netlify/functions"
functionsDirectoryOrigin = "default"
plugins = []
headers = []
redirects = []

[build]
publish = "/workspace/apps/mobile/preview-site"
publishOrigin = "default"
base = "/workspace/apps/mobile/preview-site"
functions = "/workspace/apps/mobile/preview-site/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]