/*
 * The phase gate: this TypeScript engine and the Python reference must produce
 * the same numbers on the same inputs.
 *
 * The fixtures in `fixtures/adaptive-engine-golden.json` are GENERATED by
 * running `fixtures/generate_golden.py` against `adaptive_engine.py` — they are
 * not hand-copied expectations, so a scenario cannot silently drift into
 * agreeing with the port instead of with the reference. Regenerate with:
 *
 *   python3 test/fixtures/generate_golden.py <path-to-thehybridsystem> \
 *     > test/fixtures/adaptive-engine-golden.json
 *
 * Floats are asserted at 10 decimal places per the parity brief AND, in
 * `exact`-suffixed assertions, at full precision: both languages use IEEE-754
 * doubles, so any real divergence is a porting defect to investigate, not a
 * tolerance to widen.
 */

import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

import {
  calorieTarget,
  coverageExplanation,
  estimateExpenditure,
  initialExpenditureKcal,
  linearSlope,
  macroTargets,
  nutritionIsCountable,
  periodCoverage,
  weeklyCheckIn,
  weightTrend,
  type DailyRecord,
  type EngineConfig,
  type ExpenditureEstimate,
  type IsoDate,
  type MacroTargets,
} from './index';
import { DEFAULT_ENGINE_CONFIG, engineConfig } from './types';

interface PythonRecord {
  date: string;
  calories: number | null;
  weight_kg: number | null;
  nutrition_status: string;
}

interface PythonEstimate {
  state: string;
  confidence: string;
  estimate_kcal: number | null;
  raw_estimate_kcal: number | null;
  previous_estimate_kcal: number | null;
  trend_slope_kg_per_week: number | null;
  nutrition_days: number;
  weight_days: number;
  window_start: string | null;
  window_end: string | null;
  explanation: string;
}

interface PythonMacros {
  calories: number;
  protein_g: number;
  carbs_g: number;
  fat_g: number;
  macro_calories: number;
}

interface Golden {
  source: string;
  python: string;
  engineConfig: Record<string, number>;
  weightTrend: { name: string; values: (number | null)[]; alpha: number; expected: (number | null)[] }[];
  linearSlope: { name: string; points: [string, number][]; expected: number | null }[];
  nutritionIsCountable: { record: PythonRecord; expected: boolean }[];
  periodCoverage: {
    name: string;
    records: PythonRecord[];
    start: string;
    end: string;
    expected: { nutritionDays: number; weightDays: number };
  }[];
  coverageExplanation: {
    name: string;
    records: PythonRecord[];
    expected: { enough: boolean; reasons: string[]; nutritionDays: number; weightDays: number };
  }[];
  estimateExpenditure: {
    name: string;
    records: PythonRecord[];
    previousEstimateKcal: number | null;
    expected: PythonEstimate;
  }[];
  estimateExpenditureWithConfig: {
    name: string;
    records: PythonRecord[];
    previousEstimateKcal: number | null;
    config: Record<string, number>;
    expected: PythonEstimate;
  }[];
  initialExpenditure: { name: string; input: Record<string, string | number>; expected: number }[];
  calorieTarget: { expenditureKcal: number; targetRateKgPerWeek: number; expected: number }[];
  macroTargets: {
    calories: number;
    bodyWeightKg: number;
    proteinGPerKg: number | null;
    fatGPerKg: number | null;
    expected: PythonMacros;
  }[];
  weeklyCheckIn: {
    name: string;
    records: PythonRecord[];
    previousExpenditureKcal: number | null;
    bodyWeightKg: number;
    targetRateKgPerWeek: number;
    proteinGPerKg: number;
    fatGPerKg: number;
    expected: {
      status: string;
      estimate: PythonEstimate;
      modules: { key: string; action: string }[];
      targets: PythonMacros | null;
      explanation: string;
    };
  }[];
}

const golden = JSON.parse(
  readFileSync(new URL('../test/fixtures/adaptive-engine-golden.json', import.meta.url), 'utf8'),
) as Golden;

/** snake_case config keys as the Python dataclass spells them. */
const CONFIG_KEYS: Record<string, keyof EngineConfig> = {
  kcal_per_kg: 'kcalPerKg',
  trend_alpha: 'trendAlpha',
  minimum_history_days: 'minimumHistoryDays',
  coverage_window_days: 'coverageWindowDays',
  minimum_nutrition_days_per_week: 'minimumNutritionDaysPerWeek',
  minimum_weight_days_per_week: 'minimumWeightDaysPerWeek',
  maximum_expenditure_step_kcal: 'maximumExpenditureStepKcal',
  minimum_expenditure_kcal: 'minimumExpenditureKcal',
  maximum_expenditure_kcal: 'maximumExpenditureKcal',
  default_protein_g_per_kg: 'defaultProteinGPerKg',
  default_fat_g_per_kg: 'defaultFatGPerKg',
};

function toConfig(overrides: Record<string, number>): EngineConfig {
  const mapped: Partial<EngineConfig> = {};
  for (const [pythonKey, value] of Object.entries(overrides)) {
    const key = CONFIG_KEYS[pythonKey];
    if (!key) {
      throw new Error(`Fixture names a config field the port does not have: ${pythonKey}`);
    }
    mapped[key] = value;
  }
  return engineConfig(mapped);
}

function toRecord(row: PythonRecord): DailyRecord {
  return {
    day: row.date,
    calories: row.calories,
    weightKg: row.weight_kg,
    nutritionStatus: row.nutrition_status as DailyRecord['nutritionStatus'],
  };
}

/** Compares a nullable float at 10dp and, separately, exactly. */
function expectFloat(actual: number | null, expected: number | null, label: string): void {
  if (expected === null) {
    expect(actual, label).toBeNull();
    return;
  }
  expect(actual, label).not.toBeNull();
  expect(actual as number, label).toBeCloseTo(expected, 10);
  expect(actual as number, `${label} (exact)`).toBe(expected);
}

function expectEstimate(actual: ExpenditureEstimate, expected: PythonEstimate, label: string): void {
  expect(actual.state, `${label}.state`).toBe(expected.state);
  expect(actual.confidence, `${label}.confidence`).toBe(expected.confidence);
  expectFloat(actual.estimateKcal, expected.estimate_kcal, `${label}.estimateKcal`);
  expectFloat(actual.rawEstimateKcal, expected.raw_estimate_kcal, `${label}.rawEstimateKcal`);
  expectFloat(actual.previousEstimateKcal, expected.previous_estimate_kcal, `${label}.previousEstimateKcal`);
  expectFloat(actual.trendSlopeKgPerWeek, expected.trend_slope_kg_per_week, `${label}.trendSlopeKgPerWeek`);
  expect(actual.nutritionDays, `${label}.nutritionDays`).toBe(expected.nutrition_days);
  expect(actual.weightDays, `${label}.weightDays`).toBe(expected.weight_days);
  expect(actual.windowStart, `${label}.windowStart`).toBe(expected.window_start);
  expect(actual.windowEnd, `${label}.windowEnd`).toBe(expected.window_end);
  expect(actual.explanation, `${label}.explanation`).toBe(expected.explanation);
}

function expectMacros(actual: MacroTargets, expected: PythonMacros, label: string): void {
  expectFloat(actual.calories, expected.calories, `${label}.calories`);
  expectFloat(actual.proteinG, expected.protein_g, `${label}.proteinG`);
  expectFloat(actual.carbsG, expected.carbs_g, `${label}.carbsG`);
  expectFloat(actual.fatG, expected.fat_g, `${label}.fatG`);
  expectFloat(actual.macroCalories, expected.macro_calories, `${label}.macroCalories`);
}

describe('fixtures', () => {
  it('were generated from the Python reference', () => {
    expect(golden.source).toContain('adaptive_engine.py');
    expect(golden.estimateExpenditure.length).toBeGreaterThan(0);
  });

  it('agrees on every EngineConfig default', () => {
    for (const [pythonKey, value] of Object.entries(golden.engineConfig)) {
      const key = CONFIG_KEYS[pythonKey];
      expect(key, `unmapped config field ${pythonKey}`).toBeDefined();
      expect(DEFAULT_ENGINE_CONFIG[key as keyof EngineConfig], pythonKey).toBe(value);
    }
    expect(Object.keys(golden.engineConfig).sort()).toEqual(Object.keys(CONFIG_KEYS).sort());
  });
});

describe('weightTrend parity', () => {
  for (const testCase of golden.weightTrend) {
    it(testCase.name, () => {
      const actual = weightTrend(testCase.values, testCase.alpha);
      expect(actual.length).toBe(testCase.expected.length);
      testCase.expected.forEach((expected, index) => {
        expectFloat(actual[index] ?? null, expected, `${testCase.name}[${index}]`);
      });
    });
  }
});

describe('linearSlope parity', () => {
  for (const testCase of golden.linearSlope) {
    it(testCase.name, () => {
      const points = testCase.points.map(([day, value]) => [day as IsoDate, value] as const);
      expectFloat(linearSlope(points), testCase.expected, testCase.name);
    });
  }
});

describe('nutritionIsCountable parity', () => {
  golden.nutritionIsCountable.forEach((testCase, index) => {
    it(`${testCase.record.nutrition_status}/${String(testCase.record.calories)} #${index}`, () => {
      expect(nutritionIsCountable(toRecord(testCase.record))).toBe(testCase.expected);
    });
  });
});

describe('periodCoverage parity', () => {
  for (const testCase of golden.periodCoverage) {
    it(testCase.name, () => {
      const records = testCase.records.map(toRecord).sort((a, b) => (a.day < b.day ? -1 : a.day > b.day ? 1 : 0));
      expect(periodCoverage(records, testCase.start, testCase.end)).toEqual(testCase.expected);
    });
  }
});

describe('coverageExplanation parity', () => {
  for (const testCase of golden.coverageExplanation) {
    it(testCase.name, () => {
      const records = testCase.records.map(toRecord).sort((a, b) => (a.day < b.day ? -1 : a.day > b.day ? 1 : 0));
      expect(coverageExplanation(records)).toEqual(testCase.expected);
    });
  }
});

describe('estimateExpenditure parity', () => {
  for (const testCase of golden.estimateExpenditure) {
    it(testCase.name, () => {
      const actual = estimateExpenditure(testCase.records.map(toRecord), testCase.previousEstimateKcal);
      expectEstimate(actual, testCase.expected, testCase.name);
    });
  }
});

describe('estimateExpenditure parity with non-default config', () => {
  for (const testCase of golden.estimateExpenditureWithConfig) {
    it(testCase.name, () => {
      const actual = estimateExpenditure(
        testCase.records.map(toRecord),
        testCase.previousEstimateKcal,
        toConfig(testCase.config),
      );
      expectEstimate(actual, testCase.expected, testCase.name);
    });
  }
});

describe('initialExpenditureKcal parity', () => {
  for (const testCase of golden.initialExpenditure) {
    it(testCase.name, () => {
      const input = testCase.input;
      const actual = initialExpenditureKcal({
        weightKg: input['weight_kg'] as number,
        heightCm: input['height_cm'] as number,
        ageYears: input['age_years'] as number,
        sex: input['sex'] as string | undefined,
        activityLevel: input['activity_level'] as string | undefined,
        bodyFatPct: (input['body_fat_pct'] as number | undefined) ?? null,
      });
      expectFloat(actual, testCase.expected, testCase.name);
    });
  }
});

describe('calorieTarget parity', () => {
  golden.calorieTarget.forEach((testCase, index) => {
    it(`${testCase.expenditureKcal} @ ${testCase.targetRateKgPerWeek} kg/wk #${index}`, () => {
      expectFloat(
        calorieTarget(testCase.expenditureKcal, testCase.targetRateKgPerWeek),
        testCase.expected,
        'calorieTarget',
      );
    });
  });
});

describe('macroTargets parity', () => {
  golden.macroTargets.forEach((testCase, index) => {
    it(`${testCase.calories} kcal @ ${testCase.bodyWeightKg} kg #${index}`, () => {
      const actual =
        testCase.proteinGPerKg === null || testCase.fatGPerKg === null
          ? macroTargets(testCase.calories, testCase.bodyWeightKg)
          : macroTargets(testCase.calories, testCase.bodyWeightKg, testCase.proteinGPerKg, testCase.fatGPerKg);
      expectMacros(actual, testCase.expected, `macroTargets#${index}`);
    });
  });
});

describe('weeklyCheckIn parity', () => {
  for (const testCase of golden.weeklyCheckIn) {
    it(testCase.name, () => {
      const actual = weeklyCheckIn(testCase.records.map(toRecord), {
        previousExpenditureKcal: testCase.previousExpenditureKcal,
        bodyWeightKg: testCase.bodyWeightKg,
        targetRateKgPerWeek: testCase.targetRateKgPerWeek,
        proteinGPerKg: testCase.proteinGPerKg,
        fatGPerKg: testCase.fatGPerKg,
      });
      expect(actual.status, `${testCase.name}.status`).toBe(testCase.expected.status);
      expect(actual.modules, `${testCase.name}.modules`).toEqual(testCase.expected.modules);
      expect(actual.explanation, `${testCase.name}.explanation`).toBe(testCase.expected.explanation);
      expectEstimate(actual.estimate, testCase.expected.estimate, `${testCase.name}.estimate`);
      if (testCase.expected.targets === null) {
        expect(actual.targets, `${testCase.name}.targets`).toBeNull();
      } else {
        expect(actual.targets).not.toBeNull();
        expectMacros(actual.targets as MacroTargets, testCase.expected.targets, `${testCase.name}.targets`);
      }
    });
  }
});
