const assert=require('node:assert/strict'),fs=require('node:fs'),http=require('node:http'),path=require('node:path');
const {chromium}=require('/home/agent/.local/lib/node_modules/@playwright/cli/node_modules/playwright');
(async()=>{
 const root=path.resolve(__dirname,'../../apps/athlete/conditioning'),out='/workspace/previews/flow-cleanup';fs.mkdirSync(out,{recursive:true});
 const server=http.createServer((q,r)=>{const f=q.url==='/native-plugins.js'?'native-plugins.js':'index.html';r.setHeader('Content-Type',f.endsWith('.js')?'text/javascript':'text/html');r.end(fs.readFileSync(path.join(root,f)));});await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true});try{
 const page=await browser.newPage({viewport:{width:393,height:852}}),errors=[],dialogs=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',async d=>{dialogs.push(d.message());await d.dismiss();});await page.route('https://**/*',r=>r.fulfill({status:200,contentType:'application/json',body:'{}'}));await page.goto('http://127.0.0.1:'+server.address().port);
 await page.evaluate(()=>{S.settings.liveZones={mode:'karvonen',max:190,resting:50,restingMode:'manual',version:'flow-test'};S.checkin[today()]={whoopRecovery:80};S.settings.liveWeeklyTargets={Blue:[80,100],Green:[0,0],Red:[0,0]};save();setTab('home');});
 assert.equal(await page.getByRole('heading',{name:'Cardio zones',exact:true}).count(),1);assert.match(await page.locator('#app').innerText(),/Weekly target 80–100 min/);assert.equal(await page.getByRole('button',{name:'Start training',exact:true}).count(),0);await page.screenshot({path:out+'/home.png',fullPage:true});
 await page.getByRole('button',{name:'Settings',exact:true}).click();await page.locator('#app details').evaluateAll(a=>a.forEach(d=>d.open=true));
 for(const name of ['Calculate zones','Save custom boundaries','Scheduled sessions'])assert.equal(await page.getByRole('button',{name,exact:true}).count(),0);
 assert.equal(await page.getByRole('button',{name:'Start onboarding',exact:true}).count(),1);await page.screenshot({path:out+'/settings.png',fullPage:true});
 await page.getByRole('button',{name:'Work, recovery and countdown sounds',exact:true}).click();assert.equal(await page.getByRole('heading',{name:'Settings',exact:true}).count(),1);assert.equal(await page.getByRole('heading',{name:'Methods',exact:true}).count(),0);
 await page.getByRole('button',{name:/Start Work/}).click();await page.getByRole('button',{name:/^Beep/}).click();await page.getByRole('button',{name:'Apply',exact:true}).click();await page.getByRole('button',{name:'Close alerts',exact:true}).click();assert.equal(await page.evaluate(()=>S.settings.methodAlerts[0]),'Beep');assert.equal(await page.evaluate(()=>S.tab),'me');await page.reload();assert.equal(await page.evaluate(()=>S.settings.methodAlerts[0]),'Beep');
 await page.getByRole('button',{name:'Progress',exact:true}).click();assert.equal(await page.getByLabel('History range').count(),1);assert.equal(await page.locator('.pg-tabs').count(),0);assert.equal(await page.getByRole('heading',{name:'Weekly cardio minutes',exact:true}).count(),0);await page.getByLabel('History range').selectOption('90 days');assert.equal(await page.evaluate(()=>S.progressUi.period),'90 days');await page.screenshot({path:out+'/progress.png',fullPage:true});
 await page.getByRole('button',{name:'Methods',exact:true}).click();assert.equal(await page.getByRole('button',{name:'Browse methods',exact:true}).count(),1);assert.equal(await page.getByRole('button',{name:'Blue',exact:true}).count(),0);await page.getByRole('button',{name:'Browse methods',exact:true}).click();assert.equal(await page.locator('[data-preset]').count(),4);assert.equal(await page.getByRole('button',{name:/Set Alerts/}).count(),0);assert.equal(await page.getByText('Heart Rate Zones for Today',{exact:true}).count(),0);
 for(const category of ['Blue','Green','Red']){await page.getByRole('tab',{name:category,exact:true}).click();const ids=await page.locator('[data-preset]').evaluateAll(a=>a.map(n=>n.dataset.preset));const expected=await page.evaluate(z=>Standalone.methods.filter(m=>m.zone===z).map(m=>m.id),category);assert.deepEqual(ids,expected);assert.equal(ids.length,4);assert.equal(await page.getByRole('tab',{name:category,exact:true}).getAttribute('aria-selected'),'true');}await page.getByRole('tab',{name:'Blue',exact:true}).click();await page.screenshot({path:out+'/methods.png',fullPage:true});
 await page.locator('[data-preset="blue-zone-repeats"]').click();await page.getByText('Session options',{exact:true}).click();await page.getByRole('button',{name:'Save session',exact:true}).click();assert.equal(await page.getByRole('heading',{name:'Saved session',exact:true}).count(),1);assert.equal(await page.getByRole('button',{name:'Add to calendar',exact:true}).count(),0);
 const saved=await page.evaluate(()=>({id:S.libUi.tid,config:HybridLibrary.template(S.library,S.libUi.tid).conditioningTemplate.configuration}));await page.getByRole('button',{name:'Load session',exact:true}).click();assert.equal(await page.locator('.live-dial').count(),1);assert.equal(await page.getByRole('button',{name:'Personal zones',exact:true}).count(),0);assert.equal(await page.locator('.live-pages button').count(),2);assert.deepEqual(await page.evaluate(()=>S.liveWorkout.interval.config),saved.config);assert.equal(await page.evaluate(()=>S.loggerOpen),false);
 await page.getByRole('button',{name:'Start workout',exact:true}).click();const frozen=await page.evaluate(()=>JSON.stringify(S.liveWorkout.activeZones));await page.evaluate(()=>{S.settings.liveZones.max=200;S.checkin[today()].whoopRecovery=0;LiveWorkout.view(3);});assert.equal(await page.locator('.live-weekly,.live-zone-circles').count(),0);assert.equal(await page.evaluate(()=>JSON.stringify(S.liveWorkout.activeZones)),frozen);await page.screenshot({path:out+'/workout.png',fullPage:true});
 // All twelve methods retain complete timing, including final recovery and warm-up/cool-down.
 const results=await page.evaluate(()=>Standalone.methods.map(method=>{
   S.liveWorkout=null;S.liveScreen=null;LiveWorkout.loadMethod(method,{machine:'bike',warmup:1,cooldown:1,...method.defaults});LiveWorkout.resume();LiveWorkout.confirmInterval();const c=S.liveWorkout.interval.config,total=(method.continuous?c.work:c.rounds*(c.work+c.rest))+60*(c.warmup+c.cooldown);LiveWorkout.tick(Date.now()+(total+1)*1000);return {id:method.id,done:S.liveWorkout.interval.phase==='done',completed:S.liveWorkout.intervalHistory.at(-1)?.completed};
 }));assert.equal(results.length,12);for(const r of results){assert.equal(r.done,true,r.id);assert.equal(r.completed,true,r.id);}
 // Older engine-only templates use the same logger, preserving between-round recovery and every block.
 const legacy=await page.evaluate(()=>{
   S.liveWorkout=null;let next=HybridLibrary.createTemplate(S.library,{title:'Legacy test',lane:'engine'}),id=next.templates[0].id;next=HybridLibrary.addEnginePiece(next,id,{machine:'row',title:'Repeats',structure:'intervals',workSec:2,restSec:1,rounds:2});next=HybridLibrary.addEnginePiece(next,id,{machine:'row',title:'Steady',structure:'steady',workSec:3,restSec:0,rounds:1});S.library=next;const before=JSON.stringify(S.library);LiveWorkout.loadSaved(id);const first=S.liveWorkout.interval.config;LiveWorkout.resume();LiveWorkout.confirmInterval();LiveWorkout.tick(Date.now()+5100);const nextBlock={phase:S.liveWorkout.interval.phase,title:S.liveWorkout.interval.method.title};LiveWorkout.pause();LiveWorkout.resume();LiveWorkout.confirmInterval();LiveWorkout.tick(Date.now()+3100);return {first,nextBlock,completed:S.liveWorkout.intervalHistory.filter(i=>i.completed).length,done:S.liveWorkout.interval.phase==='done',unchanged:JSON.stringify(S.library)===before,id};
 });assert.equal(legacy.first.recoverAfterLast,false);assert.deepEqual(legacy.nextBlock,{phase:'ready',title:'Steady'});assert.equal(legacy.completed,2);assert.equal(legacy.done,true);assert.equal(legacy.unchanged,true);
 // Unsupported blocks and strength-only sessions are never silently converted to cardio.
 await page.evaluate(id=>{S.liveWorkout=null;LiveWorkout.open();LiveWorkout.category('Strength');LiveWorkout.begin();LiveWorkout.loadSaved(id);},legacy.id);assert.equal(await page.evaluate(()=>S.liveWorkout.type),'Strength');assert.equal(await page.evaluate(()=>S.liveWorkout.interval),null);assert.match(dialogs.at(-1),/strength-only/);
 const unsupported=await page.evaluate(()=>{S.liveWorkout=null;const next=HybridLibrary.createTemplate(S.library,{title:'Preserved mixed template',lane:'engine'}),id=next.templates[0].id;next.templates[0].blocks=[{id:'unsupported',kind:'lift',title:'Squat'}];S.library=next;const before=JSON.stringify(S.library);LiveWorkout.loadSaved(id);return JSON.stringify(S.library)===before;});assert.equal(unsupported,true);assert.match(dialogs.at(-1),/unsupported blocks/);
 // A finished, unsaved workout remains available, rather than being replaced by a saved session.
 await page.evaluate(id=>{S.liveWorkout=null;LiveWorkout.begin();LiveWorkout.finish();S.liveWorkout.notes='Keep this';LiveWorkout.loadSaved(id);},saved.id);assert.equal(await page.evaluate(()=>S.liveWorkout.notes),'Keep this');assert.equal(await page.evaluate(()=>S.liveScreen),'ratings');
 await page.evaluate(()=>{S.liveWorkout=null;S.liveScreen=null;save();setTab('library');});await page.reload();await page.getByRole('button',{name:'Methods',exact:true}).click();assert.ok(await page.locator('.lib-card').count()>=3);assert.equal(await page.getByRole('button',{name:'Add to calendar',exact:true}).count(),0);assert.equal(await page.getByRole('button',{name:'Scheduled sessions',exact:true}).count(),0);assert.deepEqual(errors,[]);
 // Persisted navigation from the old calendar/logger cannot reopen a duplicate flow.
 await page.evaluate(()=>{S.tab='training';S.scheduledView=true;S.loggerOpen=true;S.liveWorkout=null;S.liveScreen=null;S.liveSheet='zones';S.libUi.screen='calendar';save();});await page.reload();assert.equal(await page.getByRole('heading',{name:'Workout Category',exact:true}).count(),1);assert.equal(await page.evaluate(()=>S.loggerOpen),false);assert.equal(await page.evaluate(()=>S.liveSheet),null);assert.ok(await page.evaluate(()=>S.library.templates.length)>=3);await page.getByRole('button',{name:'‹ Back',exact:true}).click();await page.getByRole('button',{name:'Methods',exact:true}).click();assert.equal(await page.getByRole('button',{name:'Browse methods',exact:true}).count(),1);
 fs.writeFileSync(out+'/results.json',JSON.stringify({methods:results,legacy,errors},null,2));console.log('PASS: single training logger, saved method and legacy engine sessions, twelve complete method timers, data preservation, frozen zones, Home-only current zones/weekly targets, one range selector, catalogue filters, Settings-only persistent sounds.');
 }finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
