import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
const window={};vm.runInNewContext(readFileSync(new URL('./hr-accounting.js',import.meta.url),'utf8'),{window});
const H=window.EngineHrAccounting,z={blue:120,green:140,red:160,max:190};
const close=(a,b)=>assert.ok(Math.abs(a-b)<1e-8,`${a} != ${b}`);
test('coverage is the interval overlap, including a delayed tick',()=>{close(H.coverage(0,5,{t:0}),3);close(H.coverage(2.75,3,{t:0}),.25);close(H.coverage(3,4,{t:0}),0);close(H.coverage(0,5,null),0);});
test('same-zone five-second dropout is explicitly estimated, including both endpoints',()=>{const r=H.interpolate({t:0,bpm:130},{t:5,bpm:134},z);assert.equal(r.eligible,true);close(r.zones.Blue,5);close(r.filledSeconds,5);});
test('linear boundary crossings split duration accurately in either direction',()=>{for(const [a,b] of [[130,150],[150,130]]){const r=H.interpolate({t:0,bpm:a},{t:10,bpm:b},z);close(r.zones.Blue,5);close(r.zones.Green,5);}const r=H.interpolate({t:0,bpm:150},{t:10,bpm:170},z);close(r.zones.Green,5);close(r.zones.Red,5);});
test('below-zone time remains unclassified and exact-boundary holds use the upper zone',()=>{const r=H.interpolate({t:0,bpm:110},{t:10,bpm:130},z);close(r.unknown,5);close(r.zones.Blue,5);close(H.interpolate({t:0,bpm:140},{t:5,bpm:140},z).zones.Green,5);});
test('long, unbracketed, suspect, invalid or normal-cadence intervals are never filled',()=>{for(const [a,b] of [[null,{t:5,bpm:130}],[{t:0,bpm:130},{t:11,bpm:130}],[{t:0,bpm:130},{t:5,bpm:170}],[{t:0,bpm:0},{t:5,bpm:130}],[{t:0,bpm:130},{t:3,bpm:130}],[{t:5,bpm:130},{t:4,bpm:130}]])assert.equal(H.interpolate(a,b,z).eligible,false);assert.equal(H.interpolate({t:0,bpm:130},{t:5,bpm:134},null).eligible,false);});
test('interpolation conserves elapsed duration across varied inputs without negative counts',()=>{for(let a=90;a<=200;a+=5)for(let delta=-20;delta<=20;delta+=5){const r=H.interpolate({t:0,bpm:a},{t:7.25,bpm:a+delta},z);close(r.filledSeconds+r.unknown,7.25);assert.ok(Object.values(r.zones).every(v=>v>=0));}});
test('legacy measured counters and new estimate counters total without rewriting original data',()=>{assert.equal(H.total({zoneSeconds:{Blue:60}},'Blue'),60);assert.equal(H.total({zoneSeconds:{Blue:60},estimatedZoneSeconds:{Blue:5}},'Blue'),65);});
