const assert=require('node:assert/strict'),fs=require('node:fs'),http=require('node:http'),path=require('node:path');
const {chromium}=require('/home/agent/.local/lib/node_modules/@playwright/cli/node_modules/playwright');
(async()=>{const root=path.resolve(__dirname,'../../apps/athlete/conditioning'),server=http.createServer((q,r)=>{const file=q.url==='/native-plugins.js'?'native-plugins.js':'index.html';r.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':'text/html');r.end(fs.readFileSync(path.join(root,file)));});await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true});try{const page=await browser.newPage({viewport:{width:393,height:852}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port);await page.getByRole('button',{name:'Settings',exact:true}).click();assert.equal(await page.getByRole('heading',{name:'Account and WHOOP sync'}).count(),1);assert.equal(await page.getByRole('button',{name:'Sign in',exact:true}).count(),1);
// A missing WHOOP baseline must not fabricate resting HR or save fake zones.
await page.getByLabel('Maximum HR',{exact:true}).fill('190');
await page.getByRole('button',{name:'Calculate zones',exact:true}).click();
assert.match(await page.locator('#karvonenError').innerText(),/Sync WHOOP/);
assert.equal(await page.evaluate(()=>S.settings.liveZones??null),null);
await page.evaluate(async()=>{await EngineApp.history({dailyMetrics:[{date:today(),rhr:50}]});render();});
assert.equal(await page.getByLabel('Resting HR override',{exact:true}).isVisible(),false);
assert.equal(await page.getByLabel('Custom Blue starts',{exact:true}).isVisible(),false);
await page.getByLabel('Maximum HR',{exact:true}).fill('190');
await page.getByRole('button',{name:'Calculate zones',exact:true}).click();
assert.deepEqual(await page.evaluate(()=>{const z=LiveWorkout.calculatedZones();return [z.blue,z.green,z.red,z.resting];}),[120,148,169,50]);
assert.equal(await page.evaluate(()=>S.settings.liveZones.restingMode),'whoop');
await page.reload();
assert.equal(await page.evaluate(()=>LiveWorkout.calculatedZones().green),148);
await page.evaluate(()=>{LiveWorkout.open();LiveWorkout.begin();LiveWorkout.resume();});
const frozen=await page.evaluate(()=>JSON.stringify(S.liveWorkout.activeZones));
await page.evaluate(async()=>{await EngineApp.history({dailyMetrics:[{date:today(),rhr:60}]});LiveWorkout.leave();setTab('me');});
await page.getByLabel('Maximum HR',{exact:true}).fill('200');
await page.getByRole('button',{name:'Calculate zones',exact:true}).click();
assert.equal(await page.evaluate(()=>JSON.stringify(S.liveWorkout.activeZones)),frozen);
assert.equal(await page.evaluate(()=>LiveWorkout.calculatedZones().max),200);
// Only an explicit in-workout zone save replaces recorded active boundaries.
await page.evaluate(()=>{S.liveScreen='workout';S.tab='training';S.liveSheet=null;LiveWorkout.zones();});
await page.getByLabel('Maximum HR',{exact:true}).fill('195');
await page.locator('details').filter({has:page.getByLabel('Resting HR override',{exact:true})}).locator('summary').click();
await page.getByLabel('Resting HR override',{exact:true}).fill('50');
await page.getByRole('button',{name:'Calculate zones',exact:true}).click();
assert.equal(await page.evaluate(()=>S.liveWorkout.activeZones.max),195);
assert.equal(await page.evaluate(()=>S.liveWorkout.activeZones.resting),50);
assert.equal(await page.evaluate(()=>S.liveWorkout.zoneHistory.at(-1).max),195);
await page.evaluate(()=>{S.checkin[today()].whoopRecovery=0;const z=LiveWorkout.calculatedZones();if(z.green>=z.baseline.green||z.red>=z.baseline.red||z.blue!==z.baseline.blue)throw Error('Recovery adjustment was lost');S.liveWorkout=null;S.liveScreen=null;S.liveSheet=null;S.settings.liveZones=null;S.checkin={};S.whoopHistory=[];setTab('me');});
await page.evaluate(async()=>{await EngineApp.history({dailyMetrics:[{date:'2026-09-28',recovery:80,hrv:48.123,rhr:54},{date:'2026-09-29',recovery:0,hrv:50.987,rhr:52}]});save();});await page.getByRole('button',{name:'Progress',exact:true}).click();await page.getByLabel('History range').selectOption('All');assert.match(await page.locator('#app').innerText(),/49.6/);await page.reload();assert.equal(await page.evaluate(()=>S.whoopHistory.length),2);assert.equal(await page.evaluate(()=>S.whoopHistory[1].recovery),0);await page.getByRole('button',{name:'Methods',exact:true}).click();await page.evaluate(()=>Standalone.browse('Blue'));await page.locator('[data-preset="tempo-intervals"]').click();await page.getByRole('button',{name:'Load Interval',exact:true}).click();await page.getByRole('button',{name:'Start workout',exact:true}).click();await page.locator('.live-interval').click();await page.getByRole('button',{name:'Confirm',exact:true}).click();assert.equal(await page.evaluate(()=>S.liveWorkout.interval.phase),'work');await page.screenshot({path:'/workspace/previews/new-apk-live.png'});await page.evaluate(()=>LiveWorkout.leave());await page.getByRole('button',{name:'Settings',exact:true}).click();await page.screenshot({path:'/workspace/previews/new-apk-settings.png',fullPage:true});assert.deepEqual(errors,[]);console.log('PASS: NEW HTML, native plugin bundle, simplified settings, Karvonen save/persistence and WHOOP baseline, missing-data gate, frozen active zones and explicit live override, WHOOP precision/history persistence, method load and live interval flow.');}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
