[build]
  base = "."
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"
