#!/usr/bin/env bash
# Best-effort cloud provision for the two product apps.
# Creates Capgo apps and Netlify sites when tokens exist. Never fails the
# repo if the cloud account cannot create resources (quota, permissions).
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/docs/product-cloud-status.md"
mkdir -p "$ROOT/docs"
{
  echo "# Product cloud provision status"
  echo
  echo "Generated by \`scripts/provision-product-clouds.sh\`. Secrets are never written here."
  echo
} > "$OUT"

log() { echo "$*" | tee -a "$OUT"; }

bash "$ROOT/scripts/rematerialize-capgo-from-vault.sh" 2>/dev/null || true
if [[ -z "${CAPGO_TOKEN:-}" && -f "$ROOT/.capgo" ]]; then
  CAPGO_TOKEN="$(cat "$ROOT/.capgo")"
fi

for PRODUCT in strength engine; do
  APP_ID="$(python3 -c "import json; print(json.load(open('$ROOT/scripts/hybrid-products.json'))['$PRODUCT']['appId'])")"
  SLUG="$(python3 -c "import json; print(json.load(open('$ROOT/scripts/hybrid-products.json'))['$PRODUCT']['netlifySlug'])")"
  NAME="$(python3 -c "import json; print(json.load(open('$ROOT/scripts/hybrid-products.json'))['$PRODUCT']['appName'])")"
  log "## $NAME"
  log
  if [[ -n "${CAPGO_TOKEN:-}" ]]; then
    log "- Capgo: attempting \`app add $APP_ID\` from product capacitor config"
    capcfg="$ROOT/$(python3 -c "import json; print(json.load(open('$ROOT/scripts/hybrid-products.json'))['$PRODUCT']['dir'])")/capacitor/capacitor.config.json"
    if (cd "$(dirname "$capcfg")" && npx --yes @capgo/cli@latest app add "$APP_ID" --apikey "$CAPGO_TOKEN" --name "$NAME") >>"$OUT" 2>&1; then
      log "- Capgo: app add reported success for \`$APP_ID\`"
      npx --yes @capgo/cli@latest channel add dogfood "$APP_ID" --apikey "$CAPGO_TOKEN" >>"$OUT" 2>&1 || true
      npx --yes @capgo/cli@latest channel add live "$APP_ID" --apikey "$CAPGO_TOKEN" >>"$OUT" 2>&1 || true
    else
      log "- Capgo: app add failed or already exists for \`$APP_ID\` (see log above). Mixed app \`com.hybrid.athlete\` is unchanged."
    fi
  else
    log "- Capgo: skipped (no token). Create app \`$APP_ID\` in Capgo Cloud, then \`PRODUCT=$PRODUCT CAPGO_BUNDLE_VERSION=1.0.0 bash scripts/ship-product-capgo.sh\`."
  fi

  if [[ -n "${NETLIFY_AUTH_TOKEN:-}" ]]; then
    log "- Netlify: attempting site create slug \`$SLUG\`"
    if npx --yes netlify-cli@26.2.0 sites:create --name "$SLUG" --auth "$NETLIFY_AUTH_TOKEN" >>"$OUT" 2>&1; then
      log "- Netlify: site \`$SLUG\` created"
    else
      log "- Netlify: could not create \`$SLUG\` (exists, quota, or permissions). Deploy with secret \`NETLIFY_SITE_ID_${PRODUCT^^}\` once the site exists."
    fi
  else
    log "- Netlify: skipped (no NETLIFY_AUTH_TOKEN). Create site \`$SLUG\`, add GitHub secret \`NETLIFY_SITE_ID_${PRODUCT^^}\`, workflow deploys on main."
  fi
  log
done

log "GitHub repos, Play listings, and hybrid1 OAuth redirect maps cannot be created from this agent (gh is read-only; Play is manual; WHOOP callback host stays thehybridengine1)."
echo "Wrote $OUT"
