// GENERATED by scripts/gen-metric-registry.mjs from every metric seed INSERT
// under supabase/migrations/ (in filename order — currently
// 20260818_strength_rebuild.sql and 20260819_phase_e_pain_metric.sql). Do
// not hand-edit — edit the migrations' seed rows and re-run the script.

export type MetricKey = 'load' | 'reps' | 'rpe' | 'rir' | 'tempo' | 'rest' | 'distance' | 'duration' | 'calories' | 'watts' | 'height' | 'pain';

export interface Metric {
  key: MetricKey;
  dimension: string;
  canonicalUnit: string;
  valueType: 'scalar' | 'range' | 'tuple' | 'duration';
  aggregation: 'sum' | 'mean' | 'max' | 'min' | 'last' | 'none';
  higherIsBetter: boolean | null;
  isLoadBearing: boolean;
}

export const METRICS: Record<MetricKey, Metric> = {
  load: {
    key: 'load',
    dimension: 'mass',
    canonicalUnit: 'kg',
    valueType: 'scalar',
    aggregation: 'sum',
    higherIsBetter: true,
    isLoadBearing: true,
  },
  reps: {
    key: 'reps',
    dimension: 'count',
    canonicalUnit: 'rep',
    valueType: 'scalar',
    aggregation: 'sum',
    higherIsBetter: true,
    isLoadBearing: false,
  },
  rpe: {
    key: 'rpe',
    dimension: 'ratio',
    canonicalUnit: 'rpe',
    valueType: 'scalar',
    aggregation: 'mean',
    higherIsBetter: null,
    isLoadBearing: false,
  },
  rir: {
    key: 'rir',
    dimension: 'ratio',
    canonicalUnit: 'rep',
    valueType: 'scalar',
    aggregation: 'mean',
    higherIsBetter: false,
    isLoadBearing: false,
  },
  tempo: {
    key: 'tempo',
    dimension: 'time',
    canonicalUnit: 's',
    valueType: 'tuple',
    aggregation: 'none',
    higherIsBetter: null,
    isLoadBearing: false,
  },
  rest: {
    key: 'rest',
    dimension: 'time',
    canonicalUnit: 's',
    valueType: 'duration',
    aggregation: 'none',
    higherIsBetter: null,
    isLoadBearing: false,
  },
  distance: {
    key: 'distance',
    dimension: 'length',
    canonicalUnit: 'm',
    valueType: 'scalar',
    aggregation: 'sum',
    higherIsBetter: true,
    isLoadBearing: false,
  },
  duration: {
    key: 'duration',
    dimension: 'time',
    canonicalUnit: 's',
    valueType: 'duration',
    aggregation: 'sum',
    higherIsBetter: null,
    isLoadBearing: false,
  },
  calories: {
    key: 'calories',
    dimension: 'energy',
    canonicalUnit: 'kcal',
    valueType: 'scalar',
    aggregation: 'sum',
    higherIsBetter: true,
    isLoadBearing: false,
  },
  watts: {
    key: 'watts',
    dimension: 'power',
    canonicalUnit: 'W',
    valueType: 'scalar',
    aggregation: 'mean',
    higherIsBetter: true,
    isLoadBearing: false,
  },
  height: {
    key: 'height',
    dimension: 'length',
    canonicalUnit: 'm',
    valueType: 'scalar',
    aggregation: 'max',
    higherIsBetter: true,
    isLoadBearing: false,
  },
  pain: {
    key: 'pain',
    dimension: 'ratio',
    canonicalUnit: 'flag',
    valueType: 'scalar',
    aggregation: 'none',
    higherIsBetter: null,
    isLoadBearing: false,
  },
};
